USE financial_doc_review;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM audit_logs;
DELETE FROM session_messages;
DELETE FROM review_sessions;
DELETE FROM approval_tasks;
DELETE FROM approval_instances;
DELETE FROM document_status_logs;
DELETE FROM document_versions;
DELETE FROM invoice_records;
DELETE FROM attachment_parse_results;
DELETE FROM risk_findings;
DELETE FROM manual_reviews;
DELETE FROM review_reports;
DELETE FROM analysis_tasks;
DELETE FROM document_line_items;
DELETE FROM document_attachments;
DELETE FROM financial_documents;
DELETE FROM role_permissions;
DELETE FROM user_roles;
DELETE FROM permissions;
DELETE FROM roles;
DELETE FROM users;
SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO roles (role_code, role_name, status) VALUES ('applicant', '单据申请人', 'active');
INSERT INTO roles (role_code, role_name, status) VALUES ('approver', '审批人员', 'active');
INSERT INTO roles (role_code, role_name, status) VALUES ('finance', '财务人员', 'active');
INSERT INTO roles (role_code, role_name, status) VALUES ('admin', '系统管理员', 'active');
INSERT INTO permissions (permission_code, permission_name, resource_type, action_type) VALUES ('doc.create', '创建单据', 'document', 'create'), ('doc.view', '查看单据', 'document', 'view'), ('doc.approve', '审批单据', 'document', 'approve'), ('rule.manage', '维护规则', 'rule', 'manage'), ('sys.manage', '系统管理', 'system', 'manage');
INSERT INTO users (id, username, display_name, password_hash, status) VALUES (1, 'wangfang', '王芳', '$pbkdf2-sha256$29000$/N/buzcGQCiFEALgnNP6Xw$3q81rqxdrqTia5P.P6sjYUNcbO/1J8KMa/hRi8zpYQo', 'active');
INSERT INTO user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO users (id, username, display_name, password_hash, status) VALUES (2, 'lilei', '李磊', '$pbkdf2-sha256$29000$AYBwLkWIcW7tHYNwTglBKA$vCuxjoNnkv61WgVc2Rre486lMBX3TQabyxs.L9.l8uU', 'active');
INSERT INTO user_roles (user_id, role_id) VALUES (2, 2);
INSERT INTO users (id, username, display_name, password_hash, status) VALUES (3, 'zhaomin', '赵敏', '$pbkdf2-sha256$29000$ZixF6D1njBECgPB.L0XI2Q$nYVEGFlg8TTbTzUfRDz0q0wTs2LOgIB/iNy/4vCH5z4', 'active');
INSERT INTO user_roles (user_id, role_id) VALUES (3, 3);
INSERT INTO users (id, username, display_name, password_hash, status) VALUES (4, 'admin', '系统管理员', '$pbkdf2-sha256$29000$s7b2XmtN6T1HyBlD6P2f0w$a00a0q9plDwNRRfCTmprXS1dof5OhsjYXV4Z7rL3URU', 'active');
INSERT INTO user_roles (user_id, role_id) VALUES (4, 4);
INSERT INTO approval_workflows (id, workflow_name, document_type, match_conditions_json, status) VALUES (1, '对公付款默认流程', '对公付款单', '{}', 'active');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (1, '初审', 1, 'approver', 'any');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (1, '财务复核', 2, 'finance', 'any');
INSERT INTO approval_workflows (id, workflow_name, document_type, match_conditions_json, status) VALUES (2, '费用报销默认流程', '费用报销单', '{}', 'active');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (2, '初审', 1, 'approver', 'any');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (2, '财务复核', 2, 'finance', 'any');
INSERT INTO approval_workflows (id, workflow_name, document_type, match_conditions_json, status) VALUES (3, '预付款默认流程', '预付款单', '{}', 'active');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (3, '初审', 1, 'approver', 'any');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (3, '财务复核', 2, 'finance', 'any');
INSERT INTO approval_workflows (id, workflow_name, document_type, match_conditions_json, status) VALUES (4, '批量付款默认流程', '批量付款单', '{}', 'active');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (4, '初审', 1, 'approver', 'any');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (4, '财务复核', 2, 'finance', 'any');
INSERT INTO approval_workflows (id, workflow_name, document_type, match_conditions_json, status) VALUES (5, '差旅报销默认流程', '差旅报销单', '{}', 'active');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (5, '初审', 1, 'approver', 'any');
INSERT INTO approval_workflow_nodes (workflow_id, node_name, node_order, approver_role, approval_mode) VALUES (5, '财务复核', 2, 'finance', 'any');
INSERT INTO audit_rules (rule_code, rule_name, rule_category, threshold, status) VALUES ('amount_consistency', '单据与发票金额一致性', 'amount', '{"amount_tolerance": 50}', 'active');
INSERT INTO audit_rules (rule_code, rule_name, rule_category, threshold, status) VALUES ('line_total_consistency', '明细与总金额一致性', 'amount', '{"tolerance": 10}', 'active');
INSERT INTO audit_rules (rule_code, rule_name, rule_category, threshold, status) VALUES ('expense_standard', '费用标准合规性', 'expense', '{"housing_standard": 600, "meal_standard": 150}', 'active');
INSERT INTO audit_rules (rule_code, rule_name, rule_category, threshold, status) VALUES ('market_price', '市场价格合理性', 'price', '{"off_ratio": 20}', 'active');
INSERT INTO audit_rules (rule_code, rule_name, rule_category, threshold, status) VALUES ('behavior_anomaly', '消费行为异常', 'behavior', '{"multiplier": 3}', 'active');
INSERT INTO audit_rules (rule_code, rule_name, rule_category, threshold, status) VALUES ('supplier_risk', '供应商风险', 'supplier', '{}', 'active');
INSERT INTO audit_rules (rule_code, rule_name, rule_category, threshold, status) VALUES ('attachment_completeness', '附件完整性', 'attachment', '{}', 'active');
INSERT INTO audit_rules (rule_code, rule_name, rule_category, threshold, status) VALUES ('duplicate_invoice', '重复票据风险', 'invoice', '{}', 'active');
INSERT INTO market_price_references (item_name, specification, region, price_min, price_max, currency, source_name, effective_date) VALUES ('商务酒店-北京', '双床房', '北京', 450, 750, 'CNY', '携程', '2026-01-01'), ('高铁票-北京-上海', '二等座', '北京', 500, 650, 'CNY', '12306', '2026-01-01');
INSERT INTO supplier_profiles (supplier_code, supplier_name, credit_status, blacklist_status, risk_tags_json, bank_accounts_json) VALUES ('SUP001', '北京华宇科技有限公司', 'normal', 'normal', '[]', '[{"account":"622200001","bank":"工商银行"}]');
INSERT INTO supplier_profiles (supplier_code, supplier_name, credit_status, blacklist_status, risk_tags_json, bank_accounts_json) VALUES ('SUP002', '上海瑞丰供应链有限公司', 'risk', 'blacklisted', '["失信","经营异常"]', '[{"account":"623300002","bank":"建设银行"}]');
